name: goodserver_gsessentials
main: goodserver.gsessentials.pkg.main
version: 1.1.0
description: This plugin is extensions of the Good Server commands. GS EssentialsXI if you will. V 1.1.0 because 1 was rankhelp; 1 was admin pay; 0 for dev build testing
commands:
  rankhelp:
    description: Information about each rank.
    usage: /rankup [name]
  ac:
    description: A better adminchat built off McMMO
    usage: /ac