name: goodserver_gsessentials
main: goodserver.gsessentials.pkg.main
version: 3.1.0
description: This plugin is extensions of the Good Server commands. GS EssentialsXI if you will. Version follows [Player Viewed Changes].[Server or Admin Changes].[Dev builds and test builds]
commands:
  rankhelp:
    description: Information about each rank.
    usage: /rankhelp [name]
  keepInv:
    description: This will be used to toggle keep inventory. If you do not want it then you may disable it
    usage: /keepinv [on | off]